#!/bin/bash
#firstboot

source /etc/firstboot.conf

if $no_run; then
    exit 0;
else
    sleep 30;
    echo timer > /sys/class/leds/nsa320:red:copy/trigger
    sleep 60;
    echo default-on > /sys/class/leds/nsa320:green:copy/trigger


    #If move to raid array is requested, do it first, reboot from array and continue.
    if $move_to_raid; then
        for r in /dev/md* ;
        do
            mdadm --stop $r;
            mdadm --remove $r;
        done

        sleep 5

        for d in /dev/sda* ;
        do
            mdadm --zero-superblock $d;
        done

        sleep 5

        for n in {1..20};
        do
           parted -s /dev/sda rm $n;
        done

        sleep 5

        parted -s /dev/sda mklabel gpt && \
        parted -s /dev/sda mkpart primary 1 $raid_part_size && \
        sleep 5

        mdadm --create /dev/md0 --run --force --metadata=0.90 --level=1 --raid-devices=2 missing /dev/sda1 && \

	# avoid ext4lazyinit if rootfs is ext4
	# https://www.thomas-krenn.com/en/wiki/Ext4_Filesystem#Lazy_Initialization
	if [[ $rfs_filesystem="ext4" ]]; then
		mkfs.$rfs_filesystem -E lazy_itable_init=0,lazy_journal_init=0 -F -L $rfs_label /dev/md0 && \
                sed -i '/DEVICE \/dev\/sd?*/d' /etc/mdadm/mdadm.conf && \
                mdadm --detail --scan >> /etc/mdadm/mdadm.conf && \
                sleep 5
	else
              mkfs.$rfs_filesystem -F -L $rfs_label /dev/md0 && \
              sed -i '/DEVICE \/dev\/sd?*/d' /etc/mdadm/mdadm.conf && \
              mdadm --detail --scan >> /etc/mdadm/mdadm.conf && \
              sleep 5
	fi
        #echo 'DEVICE /dev/sd?*' >> /etc/mdadm/mdadm.conf

        debconf-set-selections <<< "mdadm mdadm/mail_to string root"
        debconf-set-selections <<< "mdadm mdadm/initrdstart string all"
        debconf-set-selections <<< "mdadm mdadm/initrdstart_notinconf boolean true"
        debconf-set-selections <<< "mdadm mdadm/autostart boolean true"
        debconf-set-selections <<< "mdadm mdadm/autocheck boolean true"
        debconf-set-selections <<< "mdadm mdadm/start_daemon boolean true"
        dpkg-reconfigure --frontend=noninteractive mdadm ; sleep 15;

        mkimage -A arm -O linux -T kernel  -C none -a 0x00008000 -e 0x00008000 -n Linux-$kernel     -d /boot/vmlinuz-$kernel    /boot/uImage && \
        mkimage -A arm -O linux -T ramdisk -C gzip -a 0x00000000 -e 0x00000000 -n initramfs-$kernel -d /boot/initrd.img-$kernel /boot/uInitrd && \
        sed -i "s/move_to_raid=true/move_to_raid=false/" /etc/firstboot.conf && \
        mkdir /tmp/mnt && \
        mount /dev/md0 /tmp/mnt && \
        rsync -auHxq --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* --exclude=/var/tmp/* /* /tmp/mnt && \
        e2label /dev/sdb1 "oldrfs" && \
        e2label /dev/sdc1 "oldrfs" && \
        mv /boot /old-boot && \
        sync && \
        umount /tmp/mnt #&& \
        #uuid_raid_md0=$(blkid -o export /dev/md0|grep UUID|sed 's/UUID=//') && \
        #sed -i "s/LABEL=$rfs_label/UUID=\"$uuid_raid_md0\"/" /etc/fstab
        sleep 60

        #reboot

        /sbin/shutdown -h
        #exit gracefully and wait for power off
        exit 0
    fi




    #reset SSH host keys
    while [ $(pgrep -c sshd) -gt 1 ]; do
        systemctl stop ssh.service; sleep 1
        pkill --signal HUP sshd; sleep 1
        pkill --signal KILL sshd; sleep 1
    done
    rm -f /etc/ssh/ssh_host*
    ssh-keygen -Aq
    sleep 3
    systemctl start ssh.service


    #force update time with ntpdate
    systemctl stop ntp.service && ntpdate europe.pool.ntp.org
    sleep 3
    systemctl start ntp.service


    #update apt and command-not-found
    apt-get -qq update
    update-command-not-found &> /dev/null




    if $create_swap; then
        #generate 1024MB swap file and add it to fstab
        dd if=/dev/zero of=/swapfile bs=1024k count=1k
        chown root:root /swapfile
        chmod 0600 /swapfile
        mkswap /swapfile
        cat <<EOT >> /etc/fstab
/swapfile   none   swap   sw   0   0

EOT
        swapon /swapfile
    fi



     if $hdidle_from_source; then
        cd /usr/src
        git clone https://github.com/adelolmo/hd-idle.git
        cd hd-idle
        dpkg-buildpackage -us -uc -b
        dpkg -i ../hd-idle*.deb

        systemctl enable hd-idle
        sed -i 's/START_HD_IDLE=false/START_HD_IDLE=true/g' /etc/default/hd-idle
        sed -i '/HD_IDLE_OPTS/d' /etc/default/hd-idle
        echo 'HD_IDLE_OPTS="-i 3000 -l /var/log/hd-idle.log"' >> /etc/default/hd-idle

        cd -
        apt purge -y dh-golang golang-go debhelper git && apt autoremove -y
    fi


    #all done, prevent script to run on next boot
    sed -ie "s/no_run=false/no_run=true/" /etc/firstboot.conf
    systemctl disable firstboot.service


    #reboot in 1 min
    sleep 60
    reboot
    #shutdown -r

    #exit service gracefully
    exit 0
fi

